# Generated by Django 4.0.3 on 2022-03-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journal',
            table='journal',
        ),
    ]
