# Generated by Django 4.0.3 on 2022-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_alter_journal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='attachment',
            field=models.ImageField(default='media/White_full.png', upload_to='upload/'),
        ),
    ]
