# Generated by Django 4.0.3 on 2022-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0008_alter_journal_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='attachment',
            field=models.ImageField(default='media/default.png', upload_to='upload/'),
        ),
    ]
