# Generated by Django 4.0.3 on 2022-03-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0009_alter_journal_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='attachment',
            field=models.ImageField(default='default.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
