# Generated by Django 4.0.3 on 2022-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0012_remove_journal_technologies_journal_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='technologies',
        ),
        migrations.AddField(
            model_name='journal',
            name='technologies',
            field=models.ManyToManyField(to='journal_app.technology'),
        ),
    ]
