# Generated by Django 4.0.3 on 2022-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0014_remove_journal_technologies_journal_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='technologiesList',
            field=models.CharField(default=[], max_length=200),
            preserve_default=False,
        ),
    ]
