# Generated by Django 4.0.3 on 2022-03-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0017_remove_journal_technologieslist_journal_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='software',
        ),
    ]
