# Generated by Django 4.0.3 on 2022-03-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0018_remove_journal_software'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technology',
            table='technologies',
        ),
    ]
