# Generated by Django 4.0.3 on 2022-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0019_alter_technology_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='technology',
        ),
        migrations.AddField(
            model_name='journal',
            name='technologiesList',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
